# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.TimeField(blank=True, editable=False, null=True)),
                ('preview', models.ImageField(blank=True, editable=False, height_field=100, null=True, upload_to='img/', width_field=100)),
                ('status', models.IntegerField(choices=[(1, 'Готово'), (2, 'В очереди'), (3, 'На обработке'), (4, 'Ошибка обработки')], default=3)),
                ('file', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VideoCategory'),
        ),
    ]
