# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video/', validators=[manager.validators.validate_file_extension]),
        ),
    ]
